# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json tsconfig.json ./
COPY vendor ./vendor
COPY apps ./apps

RUN pnpm install --frozen-lockfile
RUN pnpm nx build fantasy-angular --configuration=production

FROM nginx:1.27-alpine AS runtime
COPY docker/nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/apps/fantasy-angular/browser /usr/share/nginx/html

EXPOSE 80
